version: '3.8'

services:
  backend:
    build:
      context: ./Techdome-backend
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - techdome-net
    environment:
      - DB_HOST=db
      - PORT=5000
    depends_on:
      - db
    command: sh -c "wait-for-it db:27017 -- npm start"
  frontend:
    build:
      context: ./Techdome-frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - techdome-net
    depends_on:
      - backend

  db:
    image: mongo:latest
    container_name: db
    volumes:
      - mongodb_data:/data/db
    networks:
      - techdome-net

networks:
  techdome-net:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
